### ISSUE TITLE
Distributed cache

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/ci#15]
At the moment the cache volume mounted at `/cache` is not shared between agents. This means that a build running on agent X cannot utilize the cache created by agent Y.

A possible solution would be to use Google Cloud Storage to for the cache. This worked well for oscoin-hs, see https://github.com/oscoin/oscoin/blob/master/scripts/ci-cache.sh. The agent could just provide GCS credentials for privileged builds so these builds can use `gutils`, or the agent would take care of actually uploading the cache.

**Comment by kim** [comment]
This is actually by design: build caches tend to be huge, and constantly
transferring them via cloud storage is orders of magnitude slower than the
local disk. On a physical machine, cache volumes are created from ZFS
snapshots, so what you see as a distinct agent is benefitting from the
local cache. Additionally, we can provision agents warm by just sending the
ZFS snapshots.

I’m not terribly excited about adding more than the bare minimum of
branching logic for “trusted” vs “untrusted” builds. Neither am I about
granting more privileges than absolutely necessary.

Also note that buildkite steps are completely independent. Their idea is to
rather have a script executing things in order than to split your pipeline
into many steps. There are cases imaginable where you do want to share
artifacts between steps, but I think that is more relevant to release
pipelines. There is a way to download the artifacts via the agent binary,
but that requires the binary to be in your Docker image. Also it needs the
agent token, which is a security concern. I’ll need to look more into their
API, perhaps we could have more granular permissions there.

**Comment by kim** [comment]
>  I’ll gather some build time data

Yes please. I think that if your caches are so volatile that you end up with a lot of work on a cache miss -- even when the cache state starts from `master` -- something is fishy about your caching strategy.

> Maybe we can define affinity for projects to agents.

Not sure. Affinity of _branch builds_ to where they were scheduled previously might be nice, but that assumes mostly-idle agents. I don't think we can influence this anyway -- the scheduling decision is made on buildkite's servers.

> Or maybe we can asynchronously distribute the master build cache.

The master build cache is agent-scoped because there is no guarantee that builds are strictly sequential. We could lift this restriction if we'd adopt a bors-style model.

**Comment by kim** [comment]
> [the buildkite-agent binary] needs the agent token, which is a security concern

Actually, that seems less of an issue than I thought. See [here](https://buildkite.com/docs/agent/v3) for what an agent can do. One can mess with the current pipeline (which is fine), start a nested agent (which is silly), or run a job (which is also silly). Wdyt?

**Comment by geigerzaehler** [comment]
> > [the buildkite-agent binary] needs the agent token, which is a security concern
> 
> Actually, that seems less of an issue than I thought. See [here](https://buildkite.com/docs/agent/v3) for what an agent can do. One can mess with the current pipeline (which is fine), start a nested agent (which is silly), or run a job (which is also silly). Wdyt?

Are you suggesting using [`buildkite artifact`](https://buildkite.com/docs/agent/v3/cli-artifact) for caching? This is something we could investigate.

**Comment by geigerzaehler** [comment]
This has been solved for the master cache volume. Because of snapshotting this also reduces the issue for branch builds.
