### ISSUE TITLE
Self-service secrets

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/ci#19]
As a developer using the CI I want to add secrets to my codebase so that a job can take a restricted action (e.g. deploy an update).

To accomplish this we can use sops. A developer can provide a sops file containing encrypted secrets in `.buildkite/secrets.yaml`. In the first stage the file is encrypted using a PGP key with the private key residing on the agent. On master builds the secrets are made available to the job using 
```bash
sops --output-type dotenv -d /build/.buildkite/secrets.yaml
```

To improve the security we can use GCP KMS to store the private key to decrypt the secrets.

**Comment by kim** [comment]
Great idea. I think we should go with KMS directly, because otherwise how do we manage that private key (with KMS, probably ;))?

**Comment by geigerzaehler** [comment]
> Great idea. I think we should go with KMS directly, because otherwise how do we manage that private key (with KMS, probably ;))?

One issue with KMS is that only symmetric keys are supported. This means that in order to create the encrypted file the developer needs access to that key. With public key crypto the devs can add secrets without having access to the KMS key. The problem here is that there is no native integration for sops so we would need to manually get the private key from KMS and load it into the GPG agent

**Comment by kim** [comment]
> One issue with KMS is that only symmetric keys are supported.

Oh ok, but that's a limitation of sops then, right?

**Comment by geigerzaehler** [comment]
> > One issue with KMS is that only symmetric keys are supported.
> 
> Oh ok, but that's a limitation of sops then, right?

Yes

**Comment by kim** [comment]
Ok, I thought about this some more, and I think there’s two concerns with
using PGP:

1. There’s no authentication. That is, anyone who knows the public master
key can encrypt to that, so we’d rely on policy enforcement in the repo
(eg. a CODEOWNERS file and GH-enforced merge policy) to prevent some random
person to sneak in altered secrets.

2. Managing that PGP key is a bit of pain in the neck: there’s a procedural
step during provisioning, and if you want to rotate the key you have to
repeat that, but then also keep around the old key to be able to decrypt
data which was not re-encrypted yet. From what I learned, the proper way
would be to keep the certifying PGP key offline, add an encryption-capable
subkey (which has to be signed), then in the event of rotation, add another
subkey and transfer that to the agent. And publish all those to a
keyserver, and add a revocation cert to the old subkey. Uagh.


Obviously, I’m more concerned about the second point, because how sensitive
are those secrets anyway, and what would you gain by replacing them with
your own.

It seems to me like centrally managed symmetric keys would actually work
out quite conveniently: we create one per repo which wants to use this
feature, and allow `cloudkms.cryptoKeyEncrypterDecrypter` to all
maintainers (plus some backup person if we really want to restrict this
within the company). The agent gets a service account, which has
`cloudkms.cryptoKeyDecrypter` privileges on all of them (note that these
keys never leave Google’s servers, so clients only need API access /
`gcloud` installed). By naming convention, the agent would choose which key
to use for a particular build.

This way, we can control who can encrypt, each team can manage their own
key rotation, and it’s even more secure if you wish because compromising
one repo wouldn’t compromise the others. Compromising the agent would leak
all secrets, of course, but that’s true either way.

Wdyt?

**Comment by geigerzaehler** [comment]
It sounds like KMS based encryption is indeed easier to operate so let’s go with that. The setup, using a key per repo, sounds sensible, too.
